services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: Password!@
    ports:
      - 3306:3306
    volumes:
      - "./mysql/database.sql:/docker-entrypoint-initdb.d/01.sql"
      - "./mysql/spring-batch-schema.sql:/docker-entrypoint-initdb.d/02.sql"
      - "./mysql/app-schema.sql:/docker-entrypoint-initdb.d/03.sql"